name: Build and Push Docker Image to GHCR

on:
  push:
    branches: ["letsmeet-*"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Tag for branches (e.g., ghcr.io/florian-doering/my-repo:feature-branch)
            type=ref,event=branch
            # Tag for tags (e.g., ghcr.io/florian-doering/my-repo:v1.0.0)
            type=ref,event=tag
            # Tag for semantic versions (e.g., ghcr.io/florian-doering/my-repo:1.0.0)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            # Tag for latest (only for tags)
            type=semver,pattern=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
<<<<<<< HEAD
          labels: ${{ steps.meta.outputs.labels }}
=======
          labels: ${{ steps.meta.outputs.labels }}
>>>>>>> letsmeet-test
